CREATE DATABASE myliss;
use myliss;

CREATE TABLE IF NOT EXISTS `pupil` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(80) NOT NULL,
	`sername` VARCHAR(255) NOT NULL,
	`phone` VARCHAR(10) NOT NULL,
	`email` VARCHAR(255) NOT NULL,
	`cost` INT NULL,
	`grade` INT NULL,
    PRIMARY KEY (`ID`)
);